$engine: 3
$onesync: on
name: CFX Default
version: 3.0.0
author: Tabarra
description: Recipe for the base resources required to run a minimal FiveM server.

tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 0210252be7c17745fa30220e12c19e0d2f19af02
    subpath: resources
    dest: ./resources

  # Download default server.cfg
  - action: download_file
    url: https://raw.githubusercontent.com/Eddyferr/CFX-Default-recipe/main/server.cfg
    path: ./server.cfg
